### ISSUE TITLE
Egress is over the account limit

### ISSUE THREAD

**Issue by BlackthornYugen** [paketo-buildpacks/syft#114]
I'm getting the following when trying to build with `paketobuildpacks/builder-jammy-tiny:0.0.38`

```bash
[INFO]     [creator]     Paketo Buildpack for Syft 1.20.0
[INFO]     [creator]       https://github.com/paketo-buildpacks/syft
[INFO]     [creator]         Downloading from https://github.com/anchore/syft/releases/download/v0.57.0/syft_0.57.0_linux_amd64.tar.gz
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency syft
[INFO]     [creator]     unable to download https://github.com/anchore/syft/releases/download/v0.57.0/syft_0.57.0_linux_amd64.tar.gz
[INFO]     [creator]     could not download https://github.com/anchore/syft/releases/download/v0.57.0/syft_0.57.0_linux_amd64.tar.gz: 503
[INFO]     [creator]     ERROR: failed to build: exit status 1
```

After searching a bit it seems that the syft project itself has an egress limit that has been reached? Similar to this discussion: https://github.com/community/community/discussions/8535

Do we need to provide a github api key or something to get around this?

**Comment by dmikusa** [comment]
We were temporarily seeing 503s in some of our CI pipelines that attempt to download binaries as well. I'm not sure what caused it, but it seems temporary as it's not happening anymore.

Are you still seeing this issue? 

For what it's worth, [you can also use dependency-mappings to work around this](https://paketo.io/docs/howto/configuration/#dependency-mappings). Essentially, you can tell the buildpack to download the binary from somewhere else.

**Comment by BlackthornYugen** [comment]
@dmikusa doesn't look like we have seen this bug in 2023 yet. Looks like it's resolved. Thanks!
